// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_6VSdHBLlGa6NDI556ZASxXJ2uUv8V28',
    appId: '1:206858636081:web:6ce92866fe5cf61ba83e10',
    messagingSenderId: '206858636081',
    projectId: 'my-flutter-notes-app-d9274',
    authDomain: 'my-flutter-notes-app-d9274.firebaseapp.com',
    storageBucket: 'my-flutter-notes-app-d9274.appspot.com',
    measurementId: 'G-E7B3FB92HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwFrFidzxDrwp3BI9HX98sLhEHMTvmg1o',
    appId: '1:206858636081:android:2cc880b4e21436b4a83e10',
    messagingSenderId: '206858636081',
    projectId: 'my-flutter-notes-app-d9274',
    storageBucket: 'my-flutter-notes-app-d9274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROeWqdyEr36ifFmaWiYeQ_ypn8XJ3RLc',
    appId: '1:206858636081:ios:5cb877c0cc8af2b7a83e10',
    messagingSenderId: '206858636081',
    projectId: 'my-flutter-notes-app-d9274',
    storageBucket: 'my-flutter-notes-app-d9274.appspot.com',
    iosClientId: '206858636081-fof4ahko91umkm2iqtgdue8c9q0g6ubg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAROeWqdyEr36ifFmaWiYeQ_ypn8XJ3RLc',
    appId: '1:206858636081:ios:5cb877c0cc8af2b7a83e10',
    messagingSenderId: '206858636081',
    projectId: 'my-flutter-notes-app-d9274',
    storageBucket: 'my-flutter-notes-app-d9274.appspot.com',
    iosClientId: '206858636081-fof4ahko91umkm2iqtgdue8c9q0g6ubg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
